# Use official OpenJDK 17
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /app

# Copy built jar
COPY target/*.jar app.jar

# Expose port (Render uses PORT env)
EXPOSE 10000

# Run Spring Boot app
ENTRYPOINT ["java","-jar","app.jar"]
